from ecdsa.curves import NIST256p

from src.elliptic_curve import EllipticCurve, mod_inv


def test_mod_inv():
    assert mod_inv(3, 11) == 4  # because 3*4 % 11 == 1
    assert mod_inv(10, 17) == 12  # because 10*12 % 17 == 1
    assert mod_inv(2, 17) == 9  # because 2*9 % 17 == 1

    # Python built-in
    assert pow(3, -1, 11) == 4
    assert pow(10, -1, 17) == 12
    assert pow(2, -1, 17) == 9


def test_elliptic_curve_1():
    # https://www.youtube.com/watch?v=Z6qLEFKDlz0
    a = 1
    b = 4
    p = 23  # Field modulus
    G = (0, 2)  # Generator point
    n = 29  # Order of the group generated by G
    E = EllipticCurve(a, b, p, G, n)
    assert E.add((0, 2), (0, 2)) == (13, 12)
    assert E.add((0, 2), (13, 12)) == (11, 9)
    assert E.mult(2, G) == (13, 12)
    assert E.mult(10, G) == (22, 5)

    s = []
    for i in range(0, n):
        s.append(E.mult(i, G))

    # print(",".join([str(d) for d in s]))
    expected = [
        (None, None),  # 0
        (0, 2),  # 1
        (13, 12),  # 2
        (11, 9),  # 3
        (1, 12),  # 4
        (7, 20),  # 5
        (9, 11),  # 6
        (15, 6),  # 7
        (14, 5),  # 8
        (4, 7),  # 9
        (22, 5),  # 10
        (10, 5),  # 11
        (17, 9),  # 12
        (8, 15),  # 13
        (18, 9),  # 14
        (18, 14),  # 15
        (8, 8),  # 16
        (17, 14),  # 17
        (10, 18),  # 18
        (22, 18),  # 19
        (4, 16),  # 20
        (14, 18),  # 21
        (15, 17),  # 22
        (9, 12),  # 23
        (7, 3),  # 24
        (1, 11),  # 25
        (11, 14),  # 26
        (13, 11),  # 27
        (0, 21),  # 28
    ]

    assert s == expected


def test_elliptic_curve_2():
    # https://www.youtube.com/watch?v=F3zzNa42-tQ

    # y^2 = x^3 + ax + b over GF(p)

    a = 2
    b = 2
    p = 17
    G = (5, 1)  # Generator point
    n = 19  # Order of the group generated by G
    E = EllipticCurve(a, b, p, G, n)

    # G+G = (6, 3)
    assert E.add(G, G) == (6, 3)
    assert E.add((5, 1), (6, 3)) == (10, 6)
    assert E.add(G, (10, 6)) == (3, 1)
    assert E.add((6, 3), (10, 6)) == (9, 16)  # 2 + 3 = 5
    assert E.add((3, 1), (9, 16)) == (7, 6)  # 4 + 5 = 9
    assert E.add((16, 13), G) == (0, 6)  # 6 + 1 = 7
    assert E.add((5, 16), G) == (None, None)  # 18 + 1 = inf

    # beta = 9
    # B = beta * G = (7,6)
    # alpha = 3
    # A = alpha * G = (10,6)
    # beta * A = 9 * 3 * G = 27 * G = 8 * G = (13,7)
    # alpha * B = 3 * 9 * G = 27 * G = 8 * G = (13,7)
    # e = dlog(6, 7, 17)

    assert E.mult(0, G) == (None, None)
    assert E.mult(1, G) == G
    assert E.mult(2, G) == (6, 3)
    assert E.mult(3, G) == (10, 6)
    assert E.mult(4, G) == (3, 1)
    assert E.mult(5, G) == (9, 16)
    assert E.mult(6, G) == (16, 13)
    assert E.mult(7, G) == (0, 6)
    assert E.mult(8, G) == (13, 7)
    assert E.mult(9, G) == (7, 6)
    assert E.mult(10, G) == (7, 11)
    assert E.mult(11, G) == (13, 10)
    assert E.mult(12, G) == (0, 11)
    assert E.mult(13, G) == (16, 4)
    assert E.mult(14, G) == (9, 1)
    assert E.mult(15, G) == (3, 16)
    assert E.mult(16, G) == (10, 11)
    assert E.mult(17, G) == (6, 14)
    assert E.mult(18, G) == (5, 16)
    assert E.mult(19, G) == (None, None)  # also E.mult(0, G)


def test_elliptic_curve_3():
    a = 1
    b = 1
    p = 13
    G = (0, 1)  # Generator point
    n = 6  # Order of the group generated by G
    E = EllipticCurve(a, b, p, G, n)

    assert E.G == (0, 1)
    assert E.add((0, 1), (0, 1)) == (10, 7)

    s = []
    for i in range(0, n):
        s.append(E.mult(i, G))

    # print(",".join([str(d) for d in s]))
    expected = [(None, None), (0, 1), (10, 7), (7, 0), (10, 6), (0, 12)]
    assert s == expected


def test_elliptic_curve_nist_p_256():
    a = -3
    b = 41058363725152142129326129780047268409114441015993725554835256314039467401291
    p = 115792089210356248762697446949407573530086143415290314195533631308867097853951
    x_G = 48439561293906451759052585252797914202762949526041747995844080717082404635286
    y_G = 36134250956749795798585127919587881956611106672985015071877198253568414405109
    G = (x_G, y_G)  # Generator point
    n = 115792089210356248762697446949407573529996955224135760342422259061068512044369  # Order of the group generated by G
    E = EllipticCurve(a, b, p, G, n)
    G2 = E.mult(2, E.G)

    G_EXPECTED = NIST256p.generator
    G2_EXPECTED = G_EXPECTED + G_EXPECTED

    assert G2[0] == G2_EXPECTED.x()
    assert G2[1] == G2_EXPECTED.y()

    GK_EXPECTED = 314159 * G_EXPECTED
    GK = E.mult(314159, E.G)

    assert GK[0] == GK_EXPECTED.x()
    assert GK[1] == GK_EXPECTED.y()


def test_encrypt_decrypt():
    p = 23  # Field modulus
    G = (0, 2)  # Generator point
    n = 29  # Order of the group generated by G
    E = EllipticCurve(1, 4, p, G, n)

    # hand shake
    a = 3  # Alice private key
    b = 4  # Bob private key

    A = E.mult(a, G)  # Alice public key
    B = E.mult(b, G)  # Bob public key

    SA = E.mult(a, B)
    SB = E.mult(b, A)
    assert SA == SB

    # encrypt (using public key B)
    M = E.mult(9, G)  # random message
    k = 2
    C1 = E.mult(k, G)  # ephemeral public key
    C2 = E.add(M, E.mult(k, B))
    assert C1 == (13, 12)
    assert C2 == (17, 14)
    # Cipher is (C1, C2)

    # decrypt (using private key b)
    # use
    # b*C1 = b*(k*G) = k*B
    # calc
    # M = C2 - k*B = C2 - b*C1 = C2 + ((n-b)%n)*C1
    M_out = E.add(C2, E.mult((n - b) % n, C1)) # using -b = (n-b)%n
    assert M == M_out